SELECT
DT_VENDA_MERCADORIA,
COMPRA.CD_MERCADORIA,
VENDA.CD_EMPRESA,
SUM(QT_VENDIDA) AS NR_UNIDADES,
SUM(QT_VENDIDA*NVL(VL_PRECO_COMPRA,0)) AS VT_VENDA,
CASE  WHEN EXTRACT(MONTH FROM DT_VENDA_MERCADORIA) <> EXTRACT(MONTH FROM SYSDATE) AND
EXTRACT(YEAR  FROM DT_VENDA_MERCADORIA) <>EXTRACT(YEAR FROM SYSDATE)
THEN  EXTRACT(MONTH FROM DT_VENDA_MERCADORIA)
WHEN EXTRACT(MONTH FROM DT_VENDA_MERCADORIA) = EXTRACT(MONTH FROM SYSDATE) AND
EXTRACT(YEAR  FROM DT_VENDA_MERCADORIA) <>EXTRACT(YEAR FROM SYSDATE)
THEN  EXTRACT(MONTH FROM DT_VENDA_MERCADORIA)
WHEN EXTRACT(MONTH FROM DT_VENDA_MERCADORIA) <> EXTRACT(MONTH FROM SYSDATE) AND
EXTRACT(YEAR  FROM DT_VENDA_MERCADORIA) =EXTRACT(YEAR FROM SYSDATE)
THEN  EXTRACT(MONTH FROM DT_VENDA_MERCADORIA)
WHEN EXTRACT(MONTH FROM DT_VENDA_MERCADORIA) = EXTRACT(MONTH FROM SYSDATE) AND
EXTRACT(YEAR  FROM DT_VENDA_MERCADORIA) =EXTRACT(YEAR FROM SYSDATE) THEN  13
END MES,
SUM(VT_FATURAMENTO_LIQUIDO) AS VT_FATURAMENTO_LIQUIDO,
SUM(VT_FATURAMENTO_BRUTO) AS VT_FATURAMENTO_BRUTO,
SUM(VT_CMV) AS VT_CMV
FROM
PRDDM.DC_MERCADORIA MERCADORIA,
PRDDM.DC_VENDA_ACUMULADA_MERCADORIA VENDA,
PRDDM.DC_FINANCEIRO_MERCADORIA FINANCEIRO,
PRDDM.DC_COMPRA_MERCADORIA COMPRA
WHERE
    VENDA.CD_MERCADORIA=MERCADORIA.CD_MERCADORIA
AND VENDA.CD_MERCADORIA=FINANCEIRO.CD_MERCADORIA
AND COMPRA.CD_MERCADORIA=FINANCEIRO.CD_MERCADORIA
AND VENDA.CD_MERCADORIA=COMPRA.CD_MERCADORIA
AND VENDA.CD_EMPRESA=FINANCEIRO.CD_EMPRESA
AND VENDA.CD_EMPRESA=COMPRA.CD_EMPRESA
AND VENDA.CD_EMPRESA=:Pnrcd
AND VENDA.DT_VENDA_MERCADORIA>= ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),-12)
AND VENDA.CD_MERCADORIA=:PnrProduto
GROUP BY DT_VENDA_MERCADORIA,COMPRA.CD_MERCADORIA,VENDA.CD_EMPRESA
ORDER BY DT_VENDA_MERCADORIA
